### ISSUE TITLE
Keybinds reference zero font size causes crash

### ISSUE THREAD

**Issue by HactarCE** [HactarCE/Hyperspeedcube#36]

**Comment by twiby** [comment]
steps to reproduce ? The issue title is not that clear for a new comer ^^

**Comment by HactarCE** [comment]
I don't remember exactly how to reproduce the original bug, but you can at least reproduce the scenario by setting the font size to zero in the yaml file. @blobinaticuber do you remember how this happened?

**Comment by blobinaticuber** [comment]
Steps to reproduce:
1. In the navbar, go to: Help > Keybinds reference
2. Open the `settings` drop down
3. Set `Max font size` to `3.0`
4. Close Hyperspeedcube
5. Reopen Hyperspeedcube
6. In the navbar, go to: Help > Keybinds reference. This time, it will produce a crash, and you will be unable to open the keybinds reference menu until you go to `hyperspeedcube.yaml` and delete the line that says `max_font_size: 3.0`

**Comment by twiby** [comment]
I tried it and I'm not getting a crash.
I tried the provided binary and compiled from source, both in Linux. I'll try Windows when I can

**Comment by HactarCE** [comment]
Fixed in v1.0.7
