### ISSUE TITLE
Missing dependencies in build instructions

### ISSUE THREAD

**Issue by twiby** [HactarCE/Hyperspeedcube#38]
Using Ubuntu 22, I had to install the following dependencies to be able to compile/run the project:
```
sudo apt install cmake libglib2.0-dev libatk1.0-dev libgtk-3-dev libxkbcommon-x11-dev
```

Whether you want to add these to the `BUILD` file or just close this issue, up to you !

**Comment by HactarCE** [comment]
Thanks! I'll add them.
