### ISSUE TITLE
Color Picker UI does not maintain which channel field is selected when typing in a value

### ISSUE THREAD

**Issue by thatcomputerguy0101** [HactarCE/Hyperspeedcube#57]
Whenever typing an RGB component value into the HSC2.0 color picker, if after any keypress the color is valid, the field becomes unselected.

https://github.com/user-attachments/assets/e3c73573-6528-4132-a8f6-a992827cd360

**Comment by thatcomputerguy0101** [comment]
Found that it is the call to focus on the hex field upon opening, in combination with the popup being "reopened" to update the value of the hex field, that is causing the text boxes to become unfocused: https://github.com/HactarCE/Hyperspeedcube/blob/365866e5f57dce371bea7bd529b2a7a022d30518/hyperspeedcube/src/gui/components/text_edit_popup.rs#L210-L212
`open` called from https://github.com/HactarCE/Hyperspeedcube/blob/365866e5f57dce371bea7bd529b2a7a022d30518/hyperspeedcube/src/gui/components/color_widgets.rs#L706-L708
Adding a separate `update` call similar to `open` but without setting `is_first_frame` to true should resolve this problem.

**Comment by HactarCE** [comment]
Thank you! You continually go above and beyond and I appreciate it so much. I'll be sure to fix this for v2.0.0-pre.15.

**Comment by thatcomputerguy0101** [comment]
Not very fixed. It seems the egui color picker no longer works at all (the hex field still works though):

https://github.com/user-attachments/assets/5548b7d8-c962-479a-9fed-d9e214512637

**Comment by HactarCE** [comment]
💀
